src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Doctrine\ORM\Mapping as ORM;

/**
 * User
 *
 * @ORM\Table(name="user", uniqueConstraints={@ORM\UniqueConstraint(name="UNIQ_8D93D649E7927C74", columns={"email"})}, indexes={@ORM\Index(name="IDX_8D93D649F92F3E70", columns={"country_id"})})
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 */
#[UniqueEntity(fields: ['email'], message: 'There is already an account with this email')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=128, nullable=false)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=128, nullable=false)
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=128, nullable=false)
     */
    private $password;

    /**
     * @var \DateTime|null
     *
     * @ORM\Column(name="register_date", type="datetime", nullable=true)
     */
    private $registerDate;

    /**
     * @var bool
     *
     * @ORM\Column(name="admin", type="boolean", nullable=false)
     */
    private $admin = '0';

    /**
     * @var bool
     *
     * @ORM\Column(name="banni", type="boolean", nullable=false)
     */
    private $banni = '0';

    /**
     * @var string|null
     *
     * @ORM\Column(name="user_id", type="string", length=128, nullable=true)
     */
    private $userId;

    /**
     * @var \Country
     *
     * @ORM\ManyToOne(targetEntity="Country")
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="country_id", referencedColumnName="id")
     * })
     */
    private $country;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Series", inversedBy="user")
     * @ORM\JoinTable(name="user_series",
     *   joinColumns={
     *     @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="series_id", referencedColumnName="id")
     *   }
     * )
     */
    private $series = array();

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="Episode", inversedBy="user")
     * @ORM\JoinTable(name="user_episode",
     *   joinColumns={
     *     @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="episode_id", referencedColumnName="id")
     *   }
     * )
     */
    private $episode = array();

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->series = new \Doctrine\Common\Collections\ArrayCollection();
        $this->episode = new \Doctrine\Common\Collections\ArrayCollection();
        $this->registerDate = new \DateTime('@'.strtotime('now'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getRegisterDate(): ?\DateTimeInterface
    {
        return $this->registerDate;
    }

    public function setRegisterDate(?\DateTimeInterface $registerDate): self
    {
        $this->registerDate = $registerDate;

        return $this;
    }

    public function isAdmin(): ?bool
    {
        return $this->admin;
    }

    public function setAdmin(bool $admin): self
    {
        $this->admin = $admin;

        return $this;
    }

    public function getBanni(): ?bool
    {
        return $this->banni;
    }

    public function setBanni(bool $banni): self
    {
        $this->banni = $banni;

        return $this;
    }

    public function getUserId(): ?string
    {
        return $this->userId;
    }

    public function setUserId(?string $userId): self
    {
        $this->userId = $userId;

        return $this;
    }

    public function getCountry(): ?Country
    {
        return $this->country;
    }

    public function setCountry(?Country $country): self
    {
        $this->country = $country;

        return $this;
    }

    /**
     * @return Collection<int, Series>
     */
    public function getSeries(): Collection
    {
        return $this->series;
    }

    public function addSeries(Series $series): self
    {
        if (!$this->series->contains($series)) {
            $this->series->add($series);
        }

        return $this;
    }

    public function removeSeries(Series $series): self
    {
        $this->series->removeElement($series);

        return $this;
    }

    /**
     * @return Collection<int, Episode>
     */
    public function getEpisode(): Collection
    {
        return $this->episode;
    }

    public function addEpisode(Episode $episode): self
    {
        if (!$this->episode->contains($episode)) {
            $this->episode->add($episode);
        }

        return $this;
    }

    public function removeEpisode(Episode $episode): self
    {
        $this->episode->removeElement($episode);

        return $this;
    }
    public function getUserIdentifier(): string { 
        return $this->getEmail(); 
    }
    public function getRoles(): array {
        if($this->admin == 1){
            return ['ROLE_ADMIN'];
        } else if ($this->banni == 1){
            return ['ROLE_BANNI'];
        }
        return ['ROLE_USER'];
    }
    public function eraseCredentials() { 

    }

    public function __toString()
    {
        return $this->name;
    }
}

src/Controller/UserController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Country;
use App\Entity\Rating;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping\Id;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Request;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
#[Route('/user')]
class UserController extends AbstractController
{
    #[Route('/list', name: 'app_user_index', methods: ['GET', 'POST'])]
    public function index(ManagerRegistry $doctrine, EntityManagerInterface $entityManager,PaginatorInterface $paginator, Request $request): Response
    {
        $em = $doctrine->getManager();
        $repository = $em->getRepository(User::class);
        if (isset($_POST['mail'])) {
            $users = $repository->findUser($_POST['mail']);
        } else {
            $users = $repository->findBy([], ['registerDate'=>'DESC']);
        }
        $usersPagines = $paginator->paginate(
            $users, // Requête contenant les données à paginer (ici nos articles)
            $request->query->getInt('page', 1), // Numéro de la page en cours, passé dans l'URL, 1 si aucune page
            8 // Nombre de résultats par page
            );
        return $this->render('user/index.html.twig', [
            'users' => $usersPagines,
        ]);
    }  

    #[Route('/', name: 'app_user_profil_index', methods: ['GET', 'POST'])]
    public function profil(ManagerRegistry $doctrine, EntityManagerInterface $entityManager): Response
    {
        if (isset($_POST['mail'])) {
            $em = $doctrine->getManager();
            $repository = $em->getRepository(User::class);
            $users = $repository->findUser($_POST['mail']);
        } else {
            $users = null;
        }

        return $this->render('user/index_profil.html.twig', [
            'users' => $users,
        ]);
    }   

    #[Route('/{userID}', name: 'app_user_ficheUtilisateur', methods: ['GET', 'POST'])]
    public function ficheUtilisateur(ManagerRegistry $doctrine,UserPasswordHasherInterface $userPasswordHasher, EntityManagerInterface $entityManager, User $userID): Response
    {
        $em = $doctrine->getManager();
        $repository = $em->getRepository(User::class);
        $user = $repository->findOneBy(['id' => $userID]);
        $repositoryCountry = $em->getRepository(Country::class);
        $ratings = $entityManager
            ->getRepository(Rating::class)
            ->getRatingById($userID);
        if(isset($_GET['nom'])){
            $user->setName($_GET['nom']);
            $em->flush();
        }
        if(isset($_GET['pays'])){
            $pays = $repositoryCountry->findOneByName($_GET['pays']);
            $user->setCountry($pays);
            $em->flush();
        }
        if(isset($_POST['nouveauMdp']) && isset($_POST['confirmation']) ){
            if($_POST['confirmation'] != $_POST['nouveauMdp']){
                return $this->render('user/changeMdp.html.twig', [
                    'user' => $user,
                    'nonValide' => "Mot de passe pas identique",
                ]); 
            }
            else{
                $user->setPassword($userPasswordHasher->hashPassword($user,$_POST['nouveauMdp']));
                $em->flush();
                return $this->render('user/fiche_utilisateur.html.twig', [
                    'user' => $user,
                    'mesAvis' => $ratings
                ]);   
            }   
        }
        
        return $this->render('user/fiche_utilisateur.html.twig', [
            'user' => $user,
            'mesAvis' => $ratings
        ]); 
    }

    #[Route('/list/{userID}', name: 'app_user_ban', methods: ['GET', 'POST'])]
    public function bannir(ManagerRegistry $doctrine, EntityManagerInterface $entityManager,PaginatorInterface $paginator, Request $request, User $userID): Response
    {
        $em = $doctrine->getManager();
        $repository = $em->getRepository(User::class);
        $userABannir = $repository->findOneBy(['id' => $userID]);
        if ($userABannir->getBanni() == 0){
            $userABannir->setBanni(1);
        }
        else {
            $userABannir->setBanni(0);
        }
        $entityManager->persist($userABannir);
        $entityManager->flush();
        return $this->redirectToRoute('app_user_index');
    } 
    #[Route('/editer/{userID}', name: 'app_user_edit', methods: ['GET', 'POST'])]
    public function editer(ManagerRegistry $doctrine, EntityManagerInterface $entityManager, User $userID): Response
    {
        $em = $doctrine->getManager();
        $repository = $em->getRepository(User::class);

        $user = $repository->findOneBy(['id' => $userID]);
        $repositoryCountry = $em->getRepository(Country::class);
        $pays = $repositoryCountry->findAll();
        
        if ($this->getUser()->getEmail() == $user->getEmail() || $this->getUser()->isAdmin()) {
            return $this->render('user/editer.html.twig', [
                'user' => $user,
                'pays' =>$pays
            ]);
        }
        else {
            return $this->redirectToRoute('app_series_index');
        }
    }
    #[Route('/nouveauMdp/{userID}', name: 'app_mdp_edit', methods: ['GET', 'POST'])]
    public function motDePasse(ManagerRegistry $doctrine, EntityManagerInterface $entityManager, User $userID): Response
    {
        $em = $doctrine->getManager();
        $repository = $em->getRepository(User::class);
        $user = $repository->findOneBy(['id' => $userID]);
        
        if ($this->getUser()->getEmail() == $user->getEmail() || $this->getUser()->isAdmin()) {
            return $this->render('user/changeMdp.html.twig', [
                'user' => $user,
                'nonValide' => ""
            ]); 
        }
        else {
            return $this->redirectToRoute('app_series_index');
        }
    }
}

templates/user/changeMdp.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <style>
        *{
            color: white;
        }

        .contain{
            margin-left: 30%;
            margin-right: 30%;
            padding: 15px;
            padding-top: 5px;
            padding-bottom: 15px;
            border-radius: 5px;
            background-color: rgba(0,0,0,0.5);
        }
        
        .profil-info{
            margin-bottom: 30px;
        }

        .profil{
            margin: 30px;
        }
        
        img{
            width: 180px;
            height: 250px;
            margin: 10px;
        }

        #mon-profil-clr{
            color: #c82333;
        }
            
        #mon-profil-clr:hover{
            font-weight: bold;
        }

        .form-control {
            margin-bottom: 10px;
        }
    </style>

    <h1>{{ nonValide }}</h1>
    <div class="contain">
        <form method="POST" action="{{path('app_user_ficheUtilisateur',{'userID':user.id})}}">
        <label>Nouveau mot de passe : </label>
        <input class="form-control"  type="password" name="nouveauMdp" required="required">
        <label>Confirmation du nouveau mot de passe :</label>
        <input class="form-control" type="password" name="confirmation" required="required">
        <input class="form-control btn-secondary btn-lg" type="submit" value="Modifier les informations du profil">
        </form>
    </div>
    </contain>
{% endblock %}

templates/user/editer.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <style>
        *{
            color: black;
        }

        label {
            color: white;
        }

        .contain{
            margin-left: 30%;
            margin-right: 30%;
            padding: 15px;
            padding-top: 5px;
            padding-bottom: 15px;
            border-radius: 5px;
            background-color: rgba(0,0,0,0.5);
        }
        
        .profil-info{
            margin-bottom: 30px;
        }

        .profil{
            margin: 30px;
        }
        
        img{
            width: 180px;
            height: 250px;
            margin: 10px;
        }

        #mon-profil-clr{
            color: #c82333;
        }
            
        #mon-profil-clr:hover{
            font-weight: bold;
        }

        .form-control {
            margin-bottom: 10px;
        }

        .form-control btn {
            width: 50px;
        }

    </style>
    <div class="contain">
        <form method="GET" action="{{path('app_user_ficheUtilisateur',{'userID':user.id})}}">
        <label>Nom : </label>
        <input class="form-control" type="text" name="nom" value="{{ user.name }}">
        <label>Pays : </label>
        <select class="form-control" name="pays">
            <option value="{{ user.country }}">{{ user.country }}</option>
            {% for pays in pays %}
            <option value="{{ pays.name }}"> {{ pays.name }} </option>
            {% endfor %}
        </select>
        <input class="form-control btn-secondary btn-lg" type="submit" value="Modifier les informations du profil ">
        </form>
    </div>
    </contain>
{% endblock %}

templates/user/fiche_utilisateur.html.twig
{% extends 'base.html.twig' %}
{% block body %}

    <style>
        *{
            color: white;
        }

        .contain{
            margin-left: 5%;
            margin-right: 5%;
            padding: 15px;
            padding-top: 5px;
            padding-bottom: 15px;
            border-radius: 5px;
            background-color: rgba(0,0,0,0.5);
        }
        
        .profil-info{
            margin-bottom: 30px;
        }

        .profil{
            margin: 30px;
        }
        
        img{
            width: 180px;
            height: 250px;
            margin: 10px;
            transition: 0.5s;
        }

        img:hover{
            width: 200px;
            height: 270px;
            margin: 10px;
            transition: 0.5s;
        }

        #mon-profil-clr{
            color: #c82333;
        }
            
        #mon-profil-clr:hover{
            font-weight: bold;
        }

        .btn {
            margin-top: 10px;
            font-size: 15px;
        }

        .container-avis-case{
            padding: 25px;
            padding-top: 15px;
            padding-bottom: 15px;
            border-radius: 5px;
            background-color: rgba(90, 90, 90, 0.8);
            margin: 10px;
        }

        .container-avis-case p{
            padding: 15px;
            border-radius: 10px;
            border: 1px solid grey;
            background-color: rgba(95, 95, 95, 0.8);
        }

        .container-avis {
            display: flex;
            flex-wrap: wrap;
            margin-top: 10px;
        }

        .container-avis>* {
            flex: 1 1 40vh;
        }

        .container-avis-case a{
            text-decoration: none;
            color: white;
            transition: 0.5s;
        }

        .container-avis-case a:hover{
            color: rgb(23, 162, 184);
            transition: 0.5s;
        }

        .date-ratings{
            font-size : 15px; 
            margin-bottom: 10px;
        }

        @media (-webkit-min-device-pixel-ratio: 2){
            .contains {
                justify-content : center;
            }
            
            h1 {
                font-size: 5em;
                text-align: center;
            }

            h2{
                font-size: 3em;
            }

            h6{
                font-size: 2em;
            }
            
            .profil a{
                font-size: 2.5em;
            }

            img{
                width: 220px;
                height: 290px;
            }
            
            h4{ 
                font-size: 2em;
            }
            
            .container-avis-case p{
                font-size: 2em;
                border-radius: 5px;
                border: 5px solid grey;
            }

            .date-ratings{
                font-size : 1.5em; 
                margin-bottom: 10px;
            }
        }
    </style>
    <div class="contain">
        <div class="profil">
            <div class="profil-info">
            <h1>Profil : {{ user.name }}</h1>
            <h6>{{ user.email }} | {{ user.country }} </h6>
            <h6>Inscrit depuis : {{ user.registerDate|date('d/m/Y') }}</h6>
            {% if app.user.email == user.email %}
                <a href="{{path('app_user_edit',{'userID': user.id})}}" class="btn btn-secondary btn-lg" role="button">Éditer mon profil</a>
                <a href="{{path('app_mdp_edit',{'userID': user.id})}}" class="btn btn-secondary btn-lg" role="button">Nouveau mot de passe</a>
            {% endif %}
        </div>


            {% set i = 0 %}
            {% for serie in user.series %}
                {% set i = i + 1 %}
            {% endfor %}

            {% if i < 1 %}
                <h2>
                <a href="{{ path('app_series_index', {'userID' : app.user})}}">Partir à la découverte de nouvelle série
                </h2>
            {% elseif i == 1 %}
                <h2>Série suivie</h2>
            {% else %}
                <h2>Séries suivies</h2>
            {% endif %}
            
            {% for series in user.series %}
                <a href="{{ path('app_series_show', {'id': series.id, 'season': '1'}) }}">{{series.showPoster}}</a>
            {% endfor %}

            <div class="container-avis">
                    {% for rating in mesAvis %}
                        <div class="container-avis-case">
                            <h4>
                                <a href="{{ path('app_series_show', {'id': rating.series.id, 'season': '1'}) }}">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-right" viewBox="0 0 16 16">
                                        <path d="M6 12.796V3.204L11.481 8 6 12.796zm.659.753 5.48-4.796a1 1 0 0 0 0-1.506L6.66 2.451C6.011 1.885 5 2.345 5 3.204v9.592a1 1 0 0 0 1.659.753z"/>
                                    </svg>
                                    {{ rating.series.title }}
                                </a>
                            </h4>
                            <h4>
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-star-fill" viewBox="0 0 16 16">
                                    <path d="M3.612 15.443c-.386.198-.824-.149-.746-.592l.83-4.73L.173 6.765c-.329-.314-.158-.888.283-.95l4.898-.696L7.538.792c.197-.39.73-.39.927 0l2.184 4.327 4.898.696c.441.062.612.636.282.95l-3.522 3.356.83 4.73c.078.443-.36.79-.746.592L8 13.187l-4.389 2.256z"/>
                                </svg>
                                {{ rating.value }}
                            </h4>
                            <div class="date-ratings">{{ rating.date|date('d/m/Y à H:m')}}</div>
                            
                            <p>{{ rating.comment }}</p>
                            
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </contain>
{% endblock %}

templates/user/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <style>
        * {
            color: white;
        }

        .user-title {
            padding-top: 20px;
            padding-bottom: 20px;
            padding-left: 20px;
        }

        .contain{
            margin-left: 5%;
            margin-right: 5%;
            padding: 15px;
            padding-top: 5px;
            padding-bottom: 15px;
            border-radius: 5px;
            background-color: rgba(0,0,0,0.5);
        }
        
        #utilisateurs-clr{
            color: #c82333;
        }
            
        #utilisateurs-clr:hover{
            font-weight: bold;
        }

        .rechercheParMail {
            display: flex;
            width: 100%;
            align-items: center;
            margin-bottom: 40px;
            justify-content: end;

        }

        .pagination a, .current{
            color: white;
            padding: 10px;
            margin: 3px;
            border: 1px solid #6c757d;
            border-radius: 4px;
            background: #6c757d;
            transition: 0.2s;
            text-decoration: none;
        }

        .pagination a:hover{
            border: 1px solid #545b62;
            background: #545b62;
            transition: 0.2s;
        }

        .textPopUp{
            color: black;
        }

        .current{
            border: 2px solid #c82333;
            background: #c82333;
        }
    </style>
    <div class="contain">
        <h1 class="user-title">Liste des utilisateurs</h1>
        <div class="rechercheParMail">
            <form method='POST'>
                <input class="form-control" type='text' name='mail' placeholder="Email" style="color: black; margin-bottom: 5px;">
                <input class="btn btn-secondary" type='submit' value='Rechercher' href='app_user_index'>
            </form>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nom</th>
                    <th>Email</th>
                    <th>Date d'inscription</th>
                    <th>Admin</th>
                    <th>Pays</th>
                    <th>Status</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td><b>{{ user.name }}</b></td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.registerDate ? user.registerDate|date('Y-m-d H:i:s') : '' }}</td>
                    <td>{{ user.admin ? 'Yes' : 'No' }}</td>
                    <td>{{ user.country }}</td>
                    {% for role in user.roles %}
                        {% if role != "ROLE_BANNI" %}
                            <td>Actif</td>
                        {% else %}
                            <td>Suspendu</td>
                        {% endif %}
                    {% endfor %}
                    <td>
                    <a href="{{ path('app_mdp_edit', {'userID': user.id}) }}" class="btn btn-primary btn-lg" role="button" aria-disabled="true">Reinitialiser mot de passe</a>
                    </td>
                    <td><a href="{{ path('app_series_index', {'_switch_user': user.email}) }}" class="btn btn-warning btn-lg" role="button" aria-disabled="true">Incarner</a></td>
                    {% for role in user.roles %}
                        {% if role != "ROLE_BANNI" %}
                                <td>
                                <button class="btn btn-warning btn-lg" data-toggle="modal" data-target="#exampleModal">
                                    Bannir
                                </button>
                                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                    <div class="modal-dialog" role="document">
                                        <div class="modal-content">
                                        <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        </button>
                                    </div>
                                    <div class="modal-body">
                                            <p class="textPopUp">Etes-vous sûr de vouloir suspendre ce compte ? </p>
                                    </div>
                                    <div class="modal-footer">
                                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Non</button>
                                            <a href="{{ path("app_user_ban", {userID : user.id}) }}" type="button" class="btn btn-primary">Oui</a>
                                    </div>
                                    </div>
                                </div>
                                </td>
                        {% else %}
                                <td><a href="{{ path("app_user_ban", {userID : user.id}) }}" class="btn btn-warning btn-lg" role="button" aria-disabled="true">Débannir</a></td>
                        {% endif %}
                    {% endfor %}
                </tr>
                
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        {{ knp_pagination_render(users) }} 
    </div>
{% endblock %}

templates/user/index_profil.html.twig
{% extends 'base.html.twig' %}

{% block title %}User index{% endblock %}

{% block body %}
    <style>
        * {
            color: white;
        }

        .user-title {
            padding-top: 20px;
            padding-bottom: 20px;
            padding-left: 20px;
        }

        .contain{
            margin-left: 5%;
            margin-right: 5%;
            padding: 15px;
            padding-top: 5px;
            padding-bottom: 15px;
            border-radius: 5px;
            background-color: rgba(0,0,0,0.5);
        }
        
        #profil-clr{
            color: #c82333;
        }
            
        #profil-clr:hover{
            font-weight: bold;
        }
        
        @media (-webkit-min-device-pixel-ratio: 2) {
            h1{
                font-size: 85px;
                text-align: center;
            }
        }

        .rechercheParMail {
            margin-bottom: 20px;
        }

        ::placeholder {
            color:rgb(110, 110, 110); 
        }
        
    </style>
    <div class="contain">
        <h1 class="user-title">Liste des utilisateurs</h1>
        <div class="rechercheParMail">
            <form method='POST'>
                <input type='text' name='mail' placeholder='user@email.fr' style="color: black; height: 46px; border-radius: 4px; border: none;">
                <input class="btn btn-secondary btn-lg" role="button" aria-disabled="true" type='submit' value='Rechercher' href='app_user_index'>
            </form>
        </div>
        <table class="table">
            <thead>
                <tr>
                    <th>Nom</th>
                    <th>Email</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td><b>{{ user.name }}</b></td>
                    <td>{{ user.email }}</td>
                    <td>
                        <a href="{{ path('app_user_ficheUtilisateur', {'userID': user.id}) }}" class="btn btn-primary btn-lg" role="button" aria-disabled="true">Consulter</a>
                    </td>
                </tr>
        
            {% else %}
                <tr>
                    <td colspan="8">no records found</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}